FROM docker.io/debian:bookworm


# To build webkit-2.41.91, we first need some dependencies:

RUN apt-get update --quiet && apt-get install --assume-yes --no-install-recommends \
    apt-transport-https \
    bubblewrap \
    build-essential \
    ca-certificates \
    ccache \
    cmake \
    curl \
    g++ \
    gettext \
    gi-docgen \
    gperf \
    libavif-dev \
    libcairo-dev \
    libdrm-dev \
    libepoxy-dev \
    libgbm-dev \
    libgcrypt20-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer1.0-dev \
    libgtk-3-dev \
    libharfbuzz-dev \
    libhyphen-dev \
    libjpeg-dev \
    libjxl-dev \
    libopenjp2-7-dev \
    libseccomp-dev \
    libsecret-1-dev \
    libsoup-3.0-dev \
    libsqlite3-dev \
    libsystemd-dev \
    libtasn1-6-dev \
    libwebp-dev \
    libwoff-dev \
    libwpe-1.0-dev \
    libwpebackend-fdo-1.0-dev \
    libxslt1-dev \
    libxt-dev \
    locales \
    lzma \
    ninja-build \
    ruby \
    sudo \
    tzdata \
    unifdef \
    xdg-dbus-proxy \
    && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
    && locale-gen en_US.UTF-8 \
    && update-ca-certificates  

RUN apt-get install --assume-yes --no-install-recommends \
    git \
    autoconf \
    texinfo \
    libxpm-dev \
    libgnutls28-dev \
    libgif-dev `# makeinfo` \
    libncurses-dev \
    libtool-bin
